apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: enterprise-gtm-starter
spec:
  chart:
    name: enterprise-gtm-starter
    chartVersion: 0.1.0
  helmVersion: v3

  useHelmInstall: true
  values:
    image:
      tag: repl{{ ConfigOption "git_version" }}
    isKurl: repl{{ IsKurl }}
    app:
      gitVersion: repl{{ ConfigOption "git_version" }}
      replicated:
        apiToken: repl{{ ConfigOption "replicated_api_token" }}
        app: repl{{ ConfigOption "replicated_app" }}
        apiOrigin: repl{{ ConfigOption "replicated_api_origin" }}
      form:
        title: repl{{ ConfigOption "title" }}
        introMarkdown: |
          repl{{ ConfigOption "introMarkdown" | nindent 10 }}
        installMarkdown: |
          repl{{ ConfigOption "installMarkdown" | nindent 10 }}
      license:
        channel: repl{{ ConfigOption "channel" }}
        expiresIn: repl{{ ConfigOption "expiresIn" }}
        type: repl{{ ConfigOption "licenseType" }}
        enableGitops: '{{repl if ConfigOptionEquals "enableGitops" "1" }}true{{repl else }}false{{repl end }}'
        enableSnapshots: '{{repl if ConfigOptionEquals "enableGitops" "1" }}true{{repl else }}false{{repl end }}'
        enableAirgap: '{{repl if ConfigOptionEquals "enableGitops" "1" }}true{{repl else }}false{{repl end }}'
  builder:
    image:
      tag: repl{{ ConfigOption "git_version" }}
