apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: enterprise-gtm-starter
spec:
  chart:
    name: enterprise-gtm-starter
    chartVersion: 0.1.0
  helmVersion: v3
  useHelmInstall: true
  values:
    image:
      tag: kots # temporary in dev, need to figure out tagging w/ GH releases...soon
    isKurl: repl{{ IsKurl }}
    app:
      replicated:
        apiToken: repl{{ ConfigOption "replicated_api_token" }}
        app: repl{{ ConfigOption "replicated_app" }}
        apiOrigin: repl{{ ConfigOption "replicated_api_origin" }}
      form:
        title: repl{{ ConfigOption "title" }}
        introMarkdown: repl{{ ConfigOption "introMarkdown" }}
        installMarkdown: repl{{ ConfigOption "installMarkdown" }}
      license:
        channel: repl{{ ConfigOption "channel" }}
        expiresIn: repl{{ ConfigOption "expiresIn" }}
        type: repl{{ ConfigOption "licenseType" }}
        enableGitops: repl{{ if ConfigOptionEquals "enableGitops" "1" }}truerepl{{ end }}
        enableSnapshots: repl{{ if ConfigOptionEquals "enableGitops" "1" }}truerepl{{ end }}
        enableAirgap: repl{{ if ConfigOptionEquals "enableGitops" "1" }}truerepl{{ end }}
  builder:
    image:
      tag: kots

