apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: enterprise-gtm-starter
spec:
  chart:
    name: enterprise-gtm-starter
    chartVersion: 0.1.0
  helmVersion: v3
  useHelmInstall: true
  values: {}
  builder:
    image:
      tag: "fake"

