---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: nginx
spec:
  title: App Name
  icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/kubernetes/icon/color/kubernetes-icon-color.png
  statusInformers:
    - deployment/nginx
  ports:
    - serviceName: "enterprise-gtm-starter"
      servicePort: 80
      localPort: 8888
      applicationUrl: "http://enterprise-gtm-starter"
