---
apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: config-sample
spec:
  groups:
    - name: replicated_settings
      title: Replicated Settings
      description: Configure connection and authentication details for creating Replicated licenses
      items:
        - name: replicated_app
          title: Replicated App
          help_text: "A Replicated App ID or App Slug from [application settings](https://vendor.replicated.com/settings)"
          type: text
          required: true
        - name: replicated_api_token
          title: Replicated API Token
          help_text: >
            A Replicated [user](https://vendor.replicated.com/account-settings) 
            or [service account](https://vendor.replicated.com/team/serviceaccounts) token
          type: password
          required: true
