---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: enterprise-gtm-starter
spec:
  title: MyApp
  icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSa6IpLT8VVWQDXoPuirydW6MC_BfKnuCOZA&usqp=CAU
