apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: support-bundle
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - logs:
        selector:
          - app=enterprise-gtm-starter
        namespace: repl{{ Namespace }}
    - runPod:
        name: check-config
        namespace: repl{{ Namespace }}
        podSpec:
          containers:
            - name: check-config
              image: ghcr.io/replicatedhq/enterprise-gtm-starter:{{repl ConfigOption "git_version" }}
              command: [/preflight-config]
              env:
                - name: REPLICATED_APP
                  value: repl{{ ConfigOption "replicated_app" }}
                - name: REPLICATED_API_TOKEN
                  value: repl{{ ConfigOption "replicated_api_token" }}
              # todo add more env vars and error detection
  analyzers:
    - textAnalyze:
        checkName: API Token
        fileName: check-config
        regex: '(401|App not found)'
        outcomes:
          - pass:
              when: "false"
              message: "API Token or App may be invalid"
          - fail:
              when: "true"
              message: "API Token or APP may be invalid"
