apiVersion: v1
kind: Secret
metadata:
  name: enterprise-gtm-starter
  labels:
    app: enterprise-gtm-starter
data:
  REPLICATED_API_TOKEN: {{ .Values.app.replicated.apiToken | b64enc }}
  REPLICATED_APP: {{ .Values.app.replicated.app | b64enc }}
  REPLICATED_API_ORIGIN: {{ .Values.app.replicated.apiOrigin | b64enc }}

  FORM_TITLE: {{ .Values.app.form.title | b64enc }}
  FORM_INTRO_MARKDOWN: {{ .Values.app.form.introMarkdown | b64enc }}
  FORM_INSTALL_MARKDOWN: {{ .Values.app.form.installMarkdown | b64enc }}

  LICENSE_CHANNEL: {{ .Values.app.license.channel | b64enc }}
  LICENSE_EXPIRE_DURATION: {{ .Values.app.license.expiresIn | b64enc }}
  LICENSE_ENABLE_GITOPS: {{ .Values.app.license.enableGitops | b64enc }}
  LICENSE_ENABLE_SNAPSHOTS: {{ .Values.app.license.enableSnapshots | b64enc }}
  LICENSE_ENABLE_AIRGAP: {{ .Values.app.license.enableAirgap | b64enc }}
