apiVersion: v1
kind: Secret
metadata:
  name: enterprise-gtm-starter
  labels:
    app: enterprise-gtm-starter
stringData:
  REPLICATED_API_TOKEN: {{ .Values.app.replicated.apiToken }}
  REPLICATED_APP: {{ .Values.app.replicated.app }}
  REPLICATED_API_ORIGIN: {{ .Values.app.replicated.apiOrigin }}

  FORM_TITLE: {{ .Values.app.form.title }}
  FORM_INTRO_MARKDOWN: {{ .Values.app.form.introMarkdown }}
  FORM_INSTALL_MARKDOWN: {{ .Values.app.form.installMarkdown }}

  LICENSE_CHANNEL: {{ .Values.app.license.channel }}
  LICENSE_EXPIRE_DURATION: {{ .Values.app.license.expiresIn }}
  LICENSE_ENABLE_GITOPS: {{ .Values.app.license.enableGitops }}
  LICENSE_ENABLE_SNAPSHOTS: {{ .Values.app.license.enableSnapshots }}
  LICENSE_ENABLE_AIRGAP: {{ .Values.app.license.enableAirgap }}
