apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-gtm-starter
  labels:
    app: enterprise-gtm-starter
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: enterprise-gtm-starter
  template:
    metadata:
      labels:
        app: enterprise-gtm-starter
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
