apiVersion: v1
kind: Service
metadata:
  name: enterprise-gtm-starter
  labels:
    app: enterprise-gtm-starter
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: enterprise-gtm-starter
